# https://github.com/goreleaser/goreleaser-action
name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  Test:
    runs-on: ubuntu-latest
    if: ${{github.repository == 'wa-lang/wa'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      # install wat2wasm
      - run: cp internal/3rdparty/wabt-go/internal/wabt-1.0.29-ubuntu/bin/wat2wasm /wa.wat2wasm.exe

      - run: make ci-test-all

  Publish:
    runs-on: ubuntu-latest
    if: ${{github.repository == 'wa-lang/wa'}}
    needs: [Test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: make build-dist

      - name: Run Releaser
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.WA_DEPLOY }}
          artifacts: "_output/*.zip,_output/*.checksums.txt"
