# https://github.com/goreleaser/goreleaser-action
name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  Test:
    runs-on: ubuntu-latest
    if: ${{github.repository == 'wa-lang/wa'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - run: make ci-test-all

  Publish:
    runs-on: ubuntu-latest
    if: ${{github.repository == 'wa-lang/wa'}}
    needs: [Test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.WA_DEPLOY }}
