# https://github.com/goreleaser/goreleaser-action
name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  Test:
    runs-on: ubuntu-latest
    if: ${{github.repository == 'wa-lang/wa'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      # install wat2wasm
      - run: sudo cp internal/3rdparty/wabt-go/internal/wabt-1.0.29-ubuntu/bin/wat2wasm /usr/local/bin/wa.wat2wasm.exe

      - run: make ci-test-all

  Publish:
    runs-on: ubuntu-latest
    if: ${{github.repository == 'wa-lang/wa'}}
    needs: [Test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          # go1.21 support wasip1/wasm
          go-version: 1.21

      - run: make build-dist

      - name: Run Releaser
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.WA_DEPLOY }}
          artifacts: "_output/*.zip,_output/*.checksums.txt"

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.WA_DEPLOY_DOCKER}}

      - name: 'Build Wa Image'
        run: |
          go run ./builder
          docker build . --tag ghcr.io/wa-lang/wa:${{ github.ref_name }}
          docker push ghcr.io/wa-lang/wa:${{ github.ref_name }}

