# 版权 @2022 凹语言 作者。保留所有权利。

name: Wa
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - "releases/*"
jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: go version
      - run: go env

      # install wat2wasm
      - run: sudo cp internal/3rdparty/wabt-go/internal/wabt-1.0.29-ubuntu/bin/wat2wasm /usr/local/bin/wa.wat2wasm.exe

      - run: make ci-test-all

      - run: go test -v -coverprofile=profile.cov ./...

      - run: go install

      - run: wa -h
      - run: cd waroot && wa run -target=wasi examples/prime
      - run: cd waroot && wa run -target=wasi hello.wa
      - run: cd waroot && wa run -target=unknown hello.wa 

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

  build-and-test-windows:
    runs-on: windows-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: go version
      - run: go env

      # install wat2wasm
      - run: copy internal/3rdparty/wabt-go/internal/wabt-1.0.29-windows/bin/wat2wasm.exe c:/wa.wat2wasm.exe

      - run: make ci-test-all

      - run: go test -v ./...

      - run: go install

      - run: wa -h
      - run: cd waroot && wa run -target=wasi examples/prime
      - run: cd waroot && wa run -target=wasi hello.wa
      - run: cd waroot && wa run -target=unknown hello.wa 

  build-and-test-macos:
    runs-on: macos-12
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: go version
      - run: go env

      # install wat2wasm
      - run: sudo cp internal/3rdparty/wabt-go/internal/wabt-1.0.29-macos/bin/wat2wasm /usr/local/bin/wa.wat2wasm.exe

      - run: make ci-test-all

      - run: go test -v ./...

      - run: go install

      - run: wa -h
      - run: cd waroot && wa run -target=wasi examples/prime
      - run: cd waroot && wa run -target=wasi hello.wa
      - run: cd waroot && wa run -target=unknown hello.wa 
